logging:
  level:
    root: info
    com.psc.sample: debug 

server:
  port: 80

spring.main.allow-bean-definition-overriding: true

spring:
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
       dialect : org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost/batchtest?characterEncoding=UTF-8
    username: root
    password: playdata
  batch:
    job:
      names: ${job.name:NONE}